apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-env-configuration
  namespace: minio-tenant
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="admin123"