apiVersion: v2
name: goldilocks
description: Helm chart for Goldilocks with ingress/gateway support
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - alias: goldilocks
    name: goldilocks
    version: 9.0.2
    repository: https://charts.fairwinds.com/stable