apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-operator-service
  namespace: minio-operator
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: minio-operator-console.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-operator
                port:
                  number: 9090